#!/bin/bash

rm -rf temp-gpg
mkdir temp-gpg
chmod 0700 temp-gpg

LANG=en_US.UTF-8

curl https://www.apache.org/dist/lucene/solr/4.10.3/KEYS | gpg --homedir temp-gpg --import &> /dev/null
gpg --homedir temp-gpg --fingerprint | grep "Key fingerprint = " | sed -r 's/\s+//g;' | cut -d= -f2

rm -rf temp-gpg

