#!/bin/bash

rm -rf temp-gpg
mkdir temp-gpg
chmod 0700 temp-gpg

LANG=en_US.UTF-8

SOLR_VERSION=$(grep "ENV SOLR_VERSION" Dockerfile | cut -d' ' -f3)

curl https://www.apache.org/dist/lucene/solr/${SOLR_VERSION}/KEYS | gpg --homedir temp-gpg --import &> /dev/null
gpg --homedir temp-gpg --fingerprint | grep "Key fingerprint = " | sed -r 's/\s+//g;' | cut -d= -f2

rm -rf temp-gpg

